[versions]
compose = "1.1.1"
coroutines = "1.6.3"
hilt = "2.43"
lifecycle = "2.5.1"
room = "2.4.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version = "1.5.1" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-preference = { module = "androidx.preference:preference-ktx", version = "1.2.0" }
google-material = { module = "com.google.android.material:material", version = "1.6.1" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version = "1.1.16" }
liveevent = { module = "com.github.hadilq:live-event", version = "1.3.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.10.0" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.19.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.3.0" }
